# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: versioning_spike_dev
  username: tahi
  password: tahi

test:
  <<: *default
  host: localhost
  database: versioning_spike_test
  username: tahi
  password: tahi
